### ISSUE TITLE
Not compatible with go 1.0.

### ISSUE THREAD

**Issue by rduplain** [gosexy/to#5]
Attempting to install `to` or the `redis` pkg which uses `to` results in:

```
to.go:241: undefined: time.ParseInLocation
```

`time.ParseInLocation` was added in go 1.1. I see this when installing either of the packages:

```
go get -u menteslibres.net/gosexy/redis
go get -u menteslibres.net/gosexy/to
```

This incompatibility was introduced in 54dec6d0. I recommend either using an alternative for this line or noting go 1.1 requirements in the README.
